name: navegacao
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cliente1.png
    - assets/images/cliente2.png
    - assets/images/detalhe_cliente.png
    - assets/images/detalhe_contato.png
    - assets/images/detalhe_empresa.png
    - assets/images/detalhe_servico.png
    - assets/images/logo.png
    - assets/images/menu_cliente.png
    - assets/images/menu_contato.png
    - assets/images/menu_empresa.png
    - assets/images/menu_servico.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
